######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
LoadEventNexus(Filename=r'/SNS/NOM/IPTS-7050/0/5427/NeXus/NOM_5427_event.nxs',OutputWorkspace='NOM_5427',ChunkNumber='1',TotalChunks='2')
CompressEvents(InputWorkspace='NOM_5427',OutputWorkspace='NOM_5427',Tolerance='0.10')
ConvertUnits(InputWorkspace='NOM_5427',OutputWorkspace='NOM_5427',Target='dSpacing',EMode='Direct')
Rebin(InputWorkspace='NOM_5427',OutputWorkspace='NOM_5427',Params='0.4,-0.0006,2.4') # -.0006 is different
#Integration(InputWorkspace='NOM_5427', OutputWorkspace='NOM_5427_int')
FindPeaks(InputWorkspace='NOM_5427', PeakPositions=(.6029,.6305,.6864,.7280,.8182,.8916,1.0754,1.2610,2.0592), BackgroundType='Flat',
          WorkspaceIndex=47090, HighBackground=True, PeaksList='NOM_5427_high')
FindPeaks(InputWorkspace='NOM_5427', PeakPositions=(.6029,.6305,.6864,.7280,.8182,.8916,1.0754,1.2610,2.0592), BackgroundType='Flat',
          WorkspaceIndex=47090, HighBackground=False, PeaksList='NOM_5427_low')
FindPeaks(InputWorkspace='NOM_5427', PeakPositions=(.6029,.6305,.6864,.7280,.8182,.8916,1.0754,1.2610,2.0592), BackgroundType='Flat',
          WorkspaceIndex=47090, HighBackground=False, PeaksList='NOM_5427_exp', PeakFunction='BackToBackExponential', RawPeakParameters=False)
FindPeaks(InputWorkspace='NOM_5427', PeakPositions=(.6029,.6305,.6864,.7280,.8182,.8916,1.0754,1.2610,2.0592), BackgroundType='Flat',
          WorkspaceIndex=47090, HighBackground=False, PeaksList='NOM_5427_exp_raw', PeakFunction='BackToBackExponential', RawPeakParameters=True)
#GetDetOffsetsMultiPeaks(InputWorkspace='NOM_5427', DReference=(.6029,.6305,.6864,.7280,.8182,.8916,1.0754,1.2610,2.0592), BackgroundType='Flat',
#                        HighBackground=True,
#                        OutputWorkspace='NOM_5427_off', MaskWorkspace='NOM_5427_mask', MaxOffset=.5)
GetDetOffsetsMultiPeaks(InputWorkspace='NOM_5427',
                        DReference=(.6029,.6305,.6864,.7280,.8182,.8916,1.0754,1.2610,20592),
                        BackgroundType='Flat', FitWindowMaxWidth=.3, HighBackground=True,
                        OutputWorkspace='NOM_5427_off', MaskWorkspace='NOM_5427_mask', MaxOffset=.5,
                        PeakFunction="Gaussian")
#ConvertUnits(InputWorkspace='NOM_5427', OutputWorkspace='NOM_5427', Target='TOF')
#ConvertToMatrixWorkspace(InputWorkspace='NOM_5427', OutputWorkspace='NOM_5427')
#AlignDetectors(InputWorkspace='NOM_5427', OutputWorkspace='NOM_5427', OffsetsWorkspace='NOM_5427_off')
