######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
LoadPreNexus(Filename="NOM_5428_runinfo.xml", ChunkNumber=1, TotalChunks=3, OutputWorkspace="NOM_5428")
Rebin(InputWorkspace="NOM_5428", OutputWorkspace="NOM_5428", Params=(300,-.0006,16667))
CompressEvents(InputWorkspace="NOM_5428", OutputWorkspace="NOM_5428", Tolerance=.1)
LoadCalFile(InputWorkspace="NOM_5428", CalFilename="/tmp/NOM_calibrate_d5427_2012_03_27.cal", WorkspaceName="NOM")
AlignDetectors(InputWorkspace="NOM_5428", OutputWorkspace="NOM_5428", OffsetsWorkspace="NOM_offsets")
DiffractionFocussing(InputWorkspace="NOM_5428", OutputWorkspace="NOM_5428", GroupingWorkspace="NOM_group", PreserveEvents=False)
StripVanadiumPeaks(InputWorkspace="NOM_5428", OutputWorkspace="NOM_5428", BackgroundType="Linear", HighBackground=True)
#Minus(LHSWorkspace='NOM_5428',RHSWorkspace='NOM_5426',OutputWorkspace='NOM_5428')
